### ISSUE TITLE
Bot just does not react to command in discord

### ISSUE THREAD

**Issue by ckocyigit** [vured/vured-bot#31]
**Describe the bug**
I've tried to switch from Sinusbot, which really got unusable in the last times and wanted to try vured bot since it seemed to be a clean solution, however after running the docker container the bot comes online (same bot token etc as sinusbot so this should work) but just does not react to the /login command.

Ive forked this repo and set the logback to DEBUG but couldn't find anything useful in the logs other than 2 ExpectionStacks (which I don't think are the cause of this misbehaviour), and some WebSocket disconnects from Discord API which seems normal to me and could have been happened due to new IP from IPS etc. 

```
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:239)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:233)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:294)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:93)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:287)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:70)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
	at io.ktor.server.netty.NettyApplicationEngineKt.getChannelClass(NettyApplicationEngine.kt:274)
	at io.ktor.server.netty.NettyApplicationEngineKt.access$getChannelClass(NettyApplicationEngine.kt:1)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create(NettyApplicationEngine.kt:245)
	at io.ktor.server.netty.NettyApplicationEngine$connectionEventGroup$2.invoke(NettyApplicationEngine.kt:88)
	at io.ktor.server.netty.NettyApplicationEngine$connectionEventGroup$2.invoke(NettyApplicationEngine.kt:28)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.ktor.server.netty.NettyApplicationEngine.getConnectionEventGroup(NettyApplicationEngine.kt)
	at io.ktor.server.netty.NettyApplicationEngine.createBootstrap(NettyApplicationEngine.kt:137)
	at io.ktor.server.netty.NettyApplicationEngine.access$createBootstrap(NettyApplicationEngine.kt:28)
	at io.ktor.server.netty.NettyApplicationEngine$bootstraps$2.invoke(NettyApplicationEngine.kt:131)
	at io.ktor.server.netty.NettyApplicationEngine$bootstraps$2.invoke(NettyApplicationEngine.kt:28)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.ktor.server.netty.NettyApplicationEngine.getBootstraps(NettyApplicationEngine.kt)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:176)
	at dev.jonaz.vured.bot.service.web.WebService.startServer(WebService.kt:33)
	at dev.jonaz.vured.bot.application.Application$start$1.invokeSuspend(Application.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:87)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:40)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at dev.jonaz.vured.bot.application.Application.start(Application.kt:36)
	at dev.jonaz.vured.bot.application.Application.<init>(Application.kt:33)
	at dev.jonaz.vured.bot.VuredKt.main(Vured.kt:13)
	at dev.jonaz.vured.bot.VuredKt.main(Vured.kt)
```

```
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @13275d8
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:353)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:344)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:294)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:93)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:287)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:70)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
	at io.ktor.server.netty.NettyApplicationEngineKt.getChannelClass(NettyApplicationEngine.kt:274)
	at io.ktor.server.netty.NettyApplicationEngineKt.access$getChannelClass(NettyApplicationEngine.kt:1)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create(NettyApplicationEngine.kt:245)
	at io.ktor.server.netty.NettyApplicationEngine$connectionEventGroup$2.invoke(NettyApplicationEngine.kt:88)
	at io.ktor.server.netty.NettyApplicationEngine$connectionEventGroup$2.invoke(NettyApplicationEngine.kt:28)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.ktor.server.netty.NettyApplicationEngine.getConnectionEventGroup(NettyApplicationEngine.kt)
	at io.ktor.server.netty.NettyApplicationEngine.createBootstrap(NettyApplicationEngine.kt:137)
	at io.ktor.server.netty.NettyApplicationEngine.access$createBootstrap(NettyApplicationEngine.kt:28)
	at io.ktor.server.netty.NettyApplicationEngine$bootstraps$2.invoke(NettyApplicationEngine.kt:131)
	at io.ktor.server.netty.NettyApplicationEngine$bootstraps$2.invoke(NettyApplicationEngine.kt:28)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.ktor.server.netty.NettyApplicationEngine.getBootstraps(NettyApplicationEngine.kt)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:176)
	at dev.jonaz.vured.bot.service.web.WebService.startServer(WebService.kt:33)
	at dev.jonaz.vured.bot.application.Application$start$1.invokeSuspend(Application.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:87)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:40)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at dev.jonaz.vured.bot.application.Application.start(Application.kt:36)
	at dev.jonaz.vured.bot.application.Application.<init>(Application.kt:33)
	at dev.jonaz.vured.bot.VuredKt.main(Vured.kt:13)
	at dev.jonaz.vured.bot.VuredKt.main(Vured.kt)

```
**To Reproduce**
1. Run Container with docker and a functional discord bot token.
2. Chat to the Bot directly or in a Group and ask for /token
3. Be sad that he is not responding ;/

**Expected behavior**
Bot to respond with the jwt token

**Comment by jonaznas** [comment]
Hey 👋,

I've recently updated the bot. Can you try if the problem still exists with a new docker container? I can't reproduce the issue with the new version.

**Comment by ckocyigit** [comment]
Hey,

Ive build a new image and tried it but unfortunetaly without luck, same behaviour. Am I missing something, can it be a direct message?, Ive tried both direct and group message.

**Comment by jonaznas** [comment]
How can you chat to the bot directly? Have you tried to use the slash command on a Server?

**Comment by ckocyigit** [comment]
Within Discord, I mean Direct Messages versus messages in "Text Channels" and yes Ive tried "7login" in both cases.

**Comment by jonaznas** [comment]
Do other commands work like "/volume" or "/youtube"?

**Comment by ckocyigit** [comment]
Hi Jonas,

Ive just tried these two commands directly but without luck it seems like
the bot just won't answer. Is it possible to just log a few more for
example login state, message events etc?. There are no Logs from the App
itself when increasing loglevel. The only thing Ive found out is that the
Exceptions are logged when entering a invalid bot token for example.

Jonas ***@***.***> schrieb am Di., 12. Apr. 2022, 16:13:

**Comment by ckocyigit** [comment]
It still persists, there is also not much to do wrong. There is only a handful of configuration through Environment Vars and the Bot Token is for sure correct.
