### ISSUE TITLE
WebSocket connection was closed and cannot be recovered

### ISSUE THREAD

**Issue by Nome200** [vured/vured-bot#34]
### WebSocket connection was closed and cannot be recovered
I am trying to run the bot with docker on Windows. I downloaded the code and build an image for docker via cmd ("docker build ."), but when i'm trying to run it it always says "WebSocket connection was closed and cannot be recovered due to identification issues"

Here are the logs
```
21:16:41,633 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
21:16:41,633 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
21:16:41,634 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/app/vured-bot.jar!/logback.xml]
21:16:41,638 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@1162410a - URL [jar:file:/app/vured-bot.jar!/logback.xml] is not of type file
21:16:41,681 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
21:16:41,681 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
21:16:41,684 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
21:16:41,691 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
21:16:41,743 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [io.sentry.logback.SentryAppender]
21:16:41,775 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [Sentry]
21:16:41,783 |-WARN in io.sentry.logback.SentryAppender[Sentry] - Failed to init Sentry during appender initialization: DSN is required. Use empty string to disable SDK.
21:16:41,783 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
21:16:41,783 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
21:16:41,783 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [Sentry] to Logger[ROOT]
21:16:41,783 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
21:16:41,784 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@b09fac1 - Registering current configuration as safe fallback point

2022-04-09 21:16:42 | INFO  | net.dv8tion.jda.api.JDA                       | Login Successful!
2022-04-09 21:16:42 | INFO  | n.d.jda.internal.requests.WebSocketClient     | Connected to WebSocket
2022-04-09 21:16:43 | ERROR | n.d.jda.internal.requests.WebSocketClient     | WebSocket connection was closed and cannot be recovered due to identification issues
CloseCode(4014 / Disallowed intents. Your bot might not be eligible to request a privileged intent such as GUILD_PRESENCES or GUILD_MEMBERS.)
2022-04-09 21:16:43 | ERROR | d.j.v.b.service.discord.DiscordClientService  | Was shutdown trying to await status
```

![image](https://user-images.githubusercontent.com/93295801/162592022-faef7c7f-0e90-4e24-8531-4106a761e157.png)
Those variables were set in the docker file

**Comment by Nome200** [comment]
I also tried to deploy it with Heroku but i also get the same error there

**Comment by Nome200** [comment]
i actually already solved this error myself by enabling those two in the bot section
![image](https://user-images.githubusercontent.com/93295801/162592439-de206f85-ab64-47ed-a09e-50fe451e8d93.png)
But i do still get an Application Error when trying to access it

**Comment by jonaznas** [comment]
Hey 👋,

glad to hear you've fixed the first issue. I plan to create a set up guide.
Heroku needs to set the port variable. Did you manually add an environment variable for the port? If yes remove it and try it again.

**Comment by Nome200** [comment]
Oh yes. A setup guide would be really helpful, especially for people which are not into coding at all.
No i did not add anything manually apart from the required token ans id's.

**Comment by jonaznas** [comment]
Did you use the "Deploy to Heroku" button from the README?

**Comment by Nome200** [comment]
Yeah i did

**Comment by Nome200** [comment]
Do you have any idea what could be causing the issue?

**Comment by jonaznas** [comment]
Unfortunately I was not able to reproduce the issue. I've tried it on multiple systems and also on Heroku. Can you give me more information about how you've set it up?

**Comment by Nome200** [comment]
I deployed the app to Heroku and gave it the required token and id's and nothing else. It then built the application
Nothing else actually

**Comment by Nome200** [comment]
I deployed it again using Heroku

```-----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
-----> Gradle app detected
-----> Installing JDK 17... done
-----> Building Gradle app...
-----> executing ./gradlew stage
       Downloading https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
       ...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%
       To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
       Daemon will be stopped at the end of the build```
       
       > Task :buildSrc:compileKotlin
       'compileJava' task (current target is 17) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
       
       > Task :buildSrc:compileJava NO-SOURCE
       > Task :buildSrc:compileGroovy NO-SOURCE
       > Task :buildSrc:pluginDescriptors
       > Task :buildSrc:processResources NO-SOURCE
       > Task :buildSrc:classes UP-TO-DATE
       > Task :buildSrc:inspectClassesForKotlinIC
       
       > Task :buildSrc:jar
       :jar: No valid plugin descriptors were found in META-INF/gradle-plugins
       
       > Task :buildSrc:assemble
       > Task :buildSrc:compileTestKotlin NO-SOURCE
       > Task :buildSrc:pluginUnderTestMetadata
       > Task :buildSrc:compileTestJava NO-SOURCE
       > Task :buildSrc:compileTestGroovy NO-SOURCE
       > Task :buildSrc:processTestResources NO-SOURCE
       > Task :buildSrc:testClasses UP-TO-DATE
       > Task :buildSrc:test NO-SOURCE
       > Task :buildSrc:validatePlugins
       > Task :buildSrc:check
       > Task :buildSrc:build
       > Task :processResources
       > Task :processTestResources NO-SOURCE
       
       > Task :kaptGenerateStubsKotlin
       w: Language version 1.7 is experimental, there are no backwards compatibility guarantees for new language and library features
       
       > Task :kaptKotlin
       
       > Task :compileKotlin
       w: Language version 1.7 is experimental, there are no backwards compatibility guarantees for new language and library features
       w: /tmp/build_230b1243/src/main/kotlin/dev/jonaz/vured/bot/service/application/ConfigService.kt: (53, 60): 'toUpperCase(): String' is deprecated. Use uppercase() instead.
       w: /tmp/build_230b1243/src/main/kotlin/dev/jonaz/vured/bot/service/application/SentryService.kt: (26, 85): Parameter 'hint' is never used, could be renamed to _
       
       > Task :compileJava NO-SOURCE
       > Task :classes
       > Task :inspectClassesForKotlinIC
       > Task :jar
       > Task :assemble
       > Task :kaptGenerateStubsTestKotlin NO-SOURCE
       
       > Task :kaptTestKotlin
       Annotation processors discovery from compile classpath is deprecated.
       Set 'kapt.include.compile.classpath=false' to disable discovery.
       Run the build with '--info' for more details.
       
       > Task :compileTestKotlin NO-SOURCE
       > Task :compileTestJava NO-SOURCE
       > Task :testClasses UP-TO-DATE
       > Task :test NO-SOURCE
       > Task :check UP-TO-DATE
       > Task :shadowJar
       > Task :build
       > Task :stage
       
       BUILD SUCCESSFUL in 2m 21s
       14 actionable tasks: 14 executed
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 105.3M
-----> Launching...
       Released v4
       https://unlucko-music-bot.herokuapp.com/ deployed to Heroku
```
It does say Build successful but i still get the error

```
2022-04-12T15:17:31.512746+00:00 app[web.1]: 	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
2022-04-12T15:17:31.512779+00:00 app[web.1]: 	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
2022-04-12T15:17:31.512816+00:00 app[web.1]: 	at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
2022-04-12T15:17:31.512847+00:00 app[web.1]: 	at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
2022-04-12T15:17:31.512880+00:00 app[web.1]: 	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
2022-04-12T15:17:31.512913+00:00 app[web.1]: 	... 15 more
2022-04-12T15:18:57.319158+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 90 seconds of launch
2022-04-12T15:18:57.394060+00:00 heroku[web.1]: Stopping process with SIGKILL
2022-04-12T15:18:57.542424+00:00 heroku[web.1]: Process exited with status 137
2022-04-12T15:18:57.594982+00:00 heroku[web.1]: State changed from starting to crashed
```

I didn't change anything manually

**Comment by jonaznas** [comment]
Can you see the full error trace of this? If yes can you also send it

```
2022-04-12T15:17:31.512746+00:00 app[web.1]: 	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
2022-04-12T15:17:31.512779+00:00 app[web.1]: 	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
2022-04-12T15:17:31.512816+00:00 app[web.1]: 	at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
2022-04-12T15:17:31.512847+00:00 app[web.1]: 	at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
2022-04-12T15:17:31.512880+00:00 app[web.1]: 	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
2022-04-12T15:17:31.512913+00:00 app[web.1]: 	... 15 more
2022-04-12T15:18:57.319158+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 90 seconds of launch
2022-04-12T15:18:57.394060+00:00 heroku[web.1]: Stopping process with SIGKILL
2022-04-12T15:18:57.542424+00:00 heroku[web.1]: Process exited with status 137
2022-04-12T15:18:57.594982+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by Nome200** [comment]
Yes but only right after it started. 
```
2022-04-13T22:16:53.195697+00:00 heroku[web.1]: State changed from crashed to starting
2022-04-13T22:16:57.036669+00:00 heroku[web.1]: Starting process with command `java $JAVA_OPTS -jar -Denv=prod build/libs/vured-bot.jar`
2022-04-13T22:16:57.859733+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2022-04-13T22:16:57.862821+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8 
2022-04-13T22:16:59.203464+00:00 app[web.1]: 22:16:58,618 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
2022-04-13T22:16:59.203485+00:00 app[web.1]: 22:16:58,618 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
2022-04-13T22:16:59.203486+00:00 app[web.1]: 22:16:58,618 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/app/build/libs/vured-bot.jar!/logback.xml]
2022-04-13T22:16:59.203492+00:00 app[web.1]: 22:16:58,623 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@5b43e173 - URL [jar:file:/app/build/libs/vured-bot.jar!/logback.xml] is not of type file
2022-04-13T22:16:59.203492+00:00 app[web.1]: 22:16:58,658 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
2022-04-13T22:16:59.203492+00:00 app[web.1]: 22:16:58,658 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
2022-04-13T22:16:59.203492+00:00 app[web.1]: 22:16:58,661 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
2022-04-13T22:16:59.203493+00:00 app[web.1]: 22:16:58,665 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
2022-04-13T22:16:59.203493+00:00 app[web.1]: 22:16:58,710 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [io.sentry.logback.SentryAppender]
2022-04-13T22:16:59.203494+00:00 app[web.1]: 22:16:59,194 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [Sentry]
2022-04-13T22:16:59.203494+00:00 app[web.1]: 22:16:59,200 |-WARN in io.sentry.logback.SentryAppender[Sentry] - Failed to init Sentry during appender initialization: DSN is required. Use empty string to disable SDK.
2022-04-13T22:16:59.203494+00:00 app[web.1]: 22:16:59,200 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
2022-04-13T22:16:59.203494+00:00 app[web.1]: 22:16:59,200 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
2022-04-13T22:16:59.203494+00:00 app[web.1]: 22:16:59,201 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [Sentry] to Logger[ROOT]
2022-04-13T22:16:59.203495+00:00 app[web.1]: 22:16:59,201 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
2022-04-13T22:16:59.203495+00:00 app[web.1]: 22:16:59,201 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@28f8e165 - Registering current configuration as safe fallback point
2022-04-13T22:16:59.203495+00:00 app[web.1]: 
2022-04-13T22:17:00.591275+00:00 app[web.1]: [37m2022-04-13 22:17:00[0;39m | [34mINFO [0;39m | [37mnet.dv8tion.jda.api.JDA                      [0;39m | Login Successful!
2022-04-13T22:17:00.818546+00:00 app[web.1]: [37m2022-04-13 22:17:00[0;39m | [34mINFO [0;39m | [37mn.d.jda.internal.requests.WebSocketClient    [0;39m | Connected to WebSocket
2022-04-13T22:17:01.109159+00:00 app[web.1]: [37m2022-04-13 22:17:01[0;39m | [34mINFO [0;39m | [37mnet.dv8tion.jda.api.JDA                      [0;39m | Finished Loading!
2022-04-13T22:17:01.356105+00:00 app[web.1]: Exception in thread "main" net.dv8tion.jda.api.exceptions.ErrorResponseException: 50001: Missing Access
2022-04-13T22:17:01.356207+00:00 app[web.1]: 	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
2022-04-13T22:17:01.356228+00:00 app[web.1]: 	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:633)
2022-04-13T22:17:01.356245+00:00 app[web.1]: 	at dev.jonaz.vured.bot.service.discord.SlashCommandService.initCommands(SlashCommandService.kt:35)
2022-04-13T22:17:01.356263+00:00 app[web.1]: 	at dev.jonaz.vured.bot.application.Application$start$1.invokeSuspend(Application.kt:43)
2022-04-13T22:17:01.356279+00:00 app[web.1]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-04-13T22:17:01.356298+00:00 app[web.1]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-04-13T22:17:01.356315+00:00 app[web.1]: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
2022-04-13T22:17:01.356356+00:00 app[web.1]: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
2022-04-13T22:17:01.356373+00:00 app[web.1]: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
2022-04-13T22:17:01.356405+00:00 app[web.1]: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2022-04-13T22:17:01.356426+00:00 app[web.1]: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
2022-04-13T22:17:01.356448+00:00 app[web.1]: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2022-04-13T22:17:01.356475+00:00 app[web.1]: 	at dev.jonaz.vured.bot.application.Application.start(Application.kt:36)
2022-04-13T22:17:01.356499+00:00 app[web.1]: 	at dev.jonaz.vured.bot.application.Application.<init>(Application.kt:33)
2022-04-13T22:17:01.356521+00:00 app[web.1]: 	at dev.jonaz.vured.bot.VuredKt.main(Vured.kt:13)
2022-04-13T22:17:01.356553+00:00 app[web.1]: 	at dev.jonaz.vured.bot.VuredKt.main(Vured.kt)
2022-04-13T22:17:01.356670+00:00 app[web.1]: Caused by: net.dv8tion.jda.api.exceptions.ContextException
2022-04-13T22:17:01.356724+00:00 app[web.1]: 	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
2022-04-13T22:17:01.356747+00:00 app[web.1]: 	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
2022-04-13T22:17:01.356771+00:00 app[web.1]: 	at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
2022-04-13T22:17:01.356800+00:00 app[web.1]: 	at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
2022-04-13T22:17:01.356826+00:00 app[web.1]: 	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
2022-04-13T22:17:01.356851+00:00 app[web.1]: 	... 15 more
2022-04-13T22:18:27.191699+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 90 seconds of launch
2022-04-13T22:18:27.377165+00:00 heroku[web.1]: Stopping process with SIGKILL
2022-04-13T22:18:27.540978+00:00 heroku[web.1]: Process exited with status 137
2022-04-13T22:18:27.760000+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by jonaznas** [comment]
Make sure the bot has sufficient permissions and you selected at least the following scopes to add the bot to your server.

![image](https://user-images.githubusercontent.com/48187105/163426468-fe4647b0-5b24-46c3-b34c-ec17a777a659.png)

**Comment by Nome200** [comment]
i actually gave the bot admin

**Comment by Nome200** [comment]
oh it was the applications commands permission that was missing
