### ISSUE TITLE
Error when requesting to play yt video

### ISSUE THREAD

**Issue by M0n7y5** [vured/vured-bot#42]
from docker logs ... probably missing dependency in docker container

```java
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: /tmp/lava-jni-natives/1671038922955/libconnector.so: Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/lava                                                  -jni-natives/1671038922955/libconnector.so)
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadWithFailureCheck(NativeLibraryLoader.java:88)
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.load(NativeLibraryLoader.java:69)
        at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:21)
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.getInstance(OpusDecoderLibrary.java:13)
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:20)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:193)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:177)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:93)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:46)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275)
        ... 10 common frames omitted

```

**Comment by AlexAdiaconitei** [comment]
Hello!
As [rehmedy](https://github.com/rehmedy) commented on this other [issue](https://github.com/vured/vured-bot/issues/40) it is related to the image used in the Dockerfile. The workaround he pointed out is to replace the `openjdk:17-alpine` image to `openjdk:17`. You can change it in the Dockerfile and then build the image again or you can use his fork to get it done quickly.

I am also working on my custom fork where I fixed this issue, updated the documentation and also added some extra features like playing spotify tracks and some extra commands. You can check it out [here](https://github.com/AlexAdiaconitei/vured-bot-dj-golan).

I am planning on making a pull request once I am done with my feature ideas, so if the owner of this repo accepts it these features will be here on the main repo as well.

**Comment by jonaznas** [comment]
> Hello! As [rehmedy](https://github.com/rehmedy) commented on this other [issue](https://github.com/vured/vured-bot/issues/40) it is related to the image used in the Dockerfile. The workaround he pointed out is to replace the `openjdk:17-alpine` image to `openjdk:17`. You can change it in the Dockerfile and then build the image again or you can use his fork to get it done quickly.
> 
> I am also working on my custom fork where I fixed this issue, updated the documentation and also added some extra features like playing spotify tracks and some extra commands. You can check it out [here](https://github.com/AlexAdiaconitei/vured-bot-dj-golan).
> 
> I am planning on making a pull request once I am done with my feature ideas, so if the owner of this repo accepts it these features will be here on the main repo as well.

Hey 👋,
I'm glad you found a workaround for this issue.

I just don't have enough time to maintain this project at the moment, so if you want to merge your features into the main repo I will definitely accept it.

Thanks!
